spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=GGN@2026ff

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=8R8JHfQ2mV7xN3kL9sP5dY6wE1aB4cT7uX0zR2qW8nM5vK1jH6gF9pL3sD8yN4bC

server.port=8081